// PriceCharting console-uid enumeration.
//
// Source: <https://www.pricecharting.com/api-documentation> →
// "Reference Tables → Console ID Table".
// These are documented as Marketplace API console IDs, but the search
// URL's `console-uid` parameter uses the same identifiers (verified:
// `G2` = GameBoy Color matches both surfaces).
//
// Snapshot taken: 2026-05. PriceCharting may add new consoles over
// time; refresh from the docs when releasing a new extension version.
//
// Grouping note: PriceCharting tracks region-specific SKUs as separate
// "consoles", so e.g. Playstation 2 (G7), JP Playstation 2 (G108) and
// PAL Playstation 2 (G63) are three distinct IDs. The `regionName`
// filter in this extension is independent — typically users will
// either pick a generic console-uid OR a region+console combination.

/** @typedef {{ id: string, name: string, group: string }} Console */

/** @type {Console[]} */
export const CONSOLES = [
  // ── Americas / default ─────────────────────────────────────────
  { group: "Americas", id: "G25",   name: "3DO" },
  { group: "Americas", id: "G36545",name: "Action Max" },
  { group: "Americas", id: "G46",   name: "Amiga" },
  { group: "Americas", id: "G92",   name: "Amiga CD32" },
  { group: "Americas", id: "G56",   name: "Amiibo" },
  { group: "Americas", id: "G46757",name: "Amiibo Cards" },
  { group: "Americas", id: "G70472",name: "Amstrad CPC" },
  { group: "Americas", id: "G66098",name: "Amstrad GX4000" },
  { group: "Americas", id: "G79417",name: "Apple II" },
  { group: "Americas", id: "G91",   name: "Arcadia 2001" },
  { group: "Americas", id: "G24",   name: "Atari 2600" },
  { group: "Americas", id: "G84152",name: "Atari 2800" },
  { group: "Americas", id: "G45",   name: "Atari 400" },
  { group: "Americas", id: "G31",   name: "Atari 5200" },
  { group: "Americas", id: "G33",   name: "Atari 7800" },
  { group: "Americas", id: "G26",   name: "Atari Lynx" },
  { group: "Americas", id: "G146",  name: "Atari ST" },
  { group: "Americas", id: "G72528",name: "Atari XE" },
  { group: "Americas", id: "G90",   name: "Bally Astrocade" },
  { group: "Americas", id: "G94412",name: "Bandai Playdia" },
  { group: "Americas", id: "G37",   name: "CD-i" },
  { group: "Americas", id: "G63134",name: "Casio Loopy" },
  { group: "Americas", id: "G30",   name: "Colecovision" },
  { group: "Americas", id: "G72569",name: "Commodore 128" },
  { group: "Americas", id: "G56918",name: "Commodore 16" },
  { group: "Americas", id: "G28",   name: "Commodore 64" },
  { group: "Americas", id: "G52",   name: "Disney Infinity" },
  { group: "Americas", id: "G72005",name: "Entex Adventure Vision" },
  { group: "Americas", id: "G28704",name: "Evercade" },
  { group: "Americas", id: "G55665",name: "FM Towns Marty" },
  { group: "Americas", id: "G83",   name: "Fairchild Channel F" },
  { group: "Americas", id: "G55",   name: "Famicom" },
  { group: "Americas", id: "G117",  name: "Famicom Disk System" },
  { group: "Americas", id: "G68",   name: "Game & Watch" },
  { group: "Americas", id: "G55666",name: "Game Wave" },
  { group: "Americas", id: "G93",   name: "Game.Com" },
  { group: "Americas", id: "G49",   name: "GameBoy" },
  { group: "Americas", id: "G1",    name: "GameBoy Advance" },
  { group: "Americas", id: "G2",    name: "GameBoy Color" },
  { group: "Americas", id: "G3",    name: "Gamecube" },
  { group: "Americas", id: "G7728", name: "Gizmondo" },
  { group: "Americas", id: "G55667",name: "HyperScan" },
  { group: "Americas", id: "G27",   name: "Intellivision" },
  { group: "Americas", id: "G21",   name: "Jaguar" },
  { group: "Americas", id: "G65467",name: "Jaguar CD" },
  { group: "Americas", id: "G66470",name: "LaserActive" },
  { group: "Americas", id: "G144",  name: "Lego Dimensions" },
  { group: "Americas", id: "G81500",name: "Macintosh" },
  { group: "Americas", id: "G130",  name: "Magnavox Odyssey" },
  { group: "Americas", id: "G36",   name: "Magnavox Odyssey 2" },
  { group: "Americas", id: "G131",  name: "Magnavox Odyssey 300" },
  { group: "Americas", id: "G132",  name: "Mattel Aquarius" },
  { group: "Americas", id: "G58494",name: "MegaZone" },
  { group: "Americas", id: "G6956", name: "Microvision" },
  { group: "Americas", id: "G69",   name: "Mini Arcade" },
  { group: "Americas", id: "G42",   name: "N-Gage" },
  { group: "Americas", id: "G17",   name: "NES" },
  { group: "Americas", id: "G116",  name: "Neo Geo AES" },
  { group: "Americas", id: "G60",   name: "Neo Geo CD" },
  { group: "Americas", id: "G18",   name: "Neo Geo MVS" },
  { group: "Americas", id: "G40",   name: "Neo Geo Pocket Color" },
  { group: "Americas", id: "G39",   name: "Nintendo 3DS" },
  { group: "Americas", id: "G4",    name: "Nintendo 64" },
  { group: "Americas", id: "G5",    name: "Nintendo DS" },
  { group: "Americas", id: "G59",   name: "Nintendo Switch" },
  { group: "Americas", id: "G80178",name: "Nintendo Switch 2" },
  { group: "Americas", id: "G72978",name: "Nuon" },
  { group: "Americas", id: "G6955", name: "PC FX" },
  { group: "Americas", id: "G145",  name: "PC Games" },
  { group: "Americas", id: "G9",    name: "PSP" },
  { group: "Americas", id: "G55669",name: "Pippin" },
  { group: "Americas", id: "G6",    name: "Playstation" },
  { group: "Americas", id: "G7",    name: "Playstation 2" },
  { group: "Americas", id: "G12",   name: "Playstation 3" },
  { group: "Americas", id: "G53",   name: "Playstation 4" },
  { group: "Americas", id: "G7468", name: "Playstation 5" },
  { group: "Americas", id: "G43",   name: "Playstation Vita" },
  { group: "Americas", id: "G143",  name: "Pokemon Mini" },
  { group: "Americas", id: "G76600",name: "Polymega" },
  { group: "Americas", id: "G87937",name: "RCA Studio II" },
  { group: "Americas", id: "G91000",name: "RDI Halcyon" },
  { group: "Americas", id: "G43345",name: "Rumble U" },
  { group: "Americas", id: "G50",   name: "Sega 32X" },
  { group: "Americas", id: "G23",   name: "Sega CD" },
  { group: "Americas", id: "G16",   name: "Sega Dreamcast" },
  { group: "Americas", id: "G20",   name: "Sega Game Gear" },
  { group: "Americas", id: "G15",   name: "Sega Genesis" },
  { group: "Americas", id: "G29",   name: "Sega Master System" },
  { group: "Americas", id: "G136",  name: "Sega Pico" },
  { group: "Americas", id: "G14",   name: "Sega Saturn" },
  { group: "Americas", id: "G61110",name: "Sharp X68000" },
  { group: "Americas", id: "G77384",name: "Sinclair ZX81" },
  { group: "Americas", id: "G48",   name: "Skylanders" },
  { group: "Americas", id: "G43344",name: "Starlink" },
  { group: "Americas", id: "G60326",name: "Stoneheart" },
  { group: "Americas", id: "G66",   name: "Super Famicom" },
  { group: "Americas", id: "G13",   name: "Super Nintendo" },
  { group: "Americas", id: "G55668",name: "Supervision" },
  { group: "Americas", id: "G120",  name: "TI-99" },
  { group: "Americas", id: "G75713",name: "TRS-80" },
  { group: "Americas", id: "G51260",name: "Tapwave Zodiac" },
  { group: "Americas", id: "G43401",name: "Tiger R-Zone" },
  { group: "Americas", id: "G6927", name: "TurboGrafx CD" },
  { group: "Americas", id: "G19",   name: "TurboGrafx-16" },
  { group: "Americas", id: "G75110",name: "UB Funkeys" },
  { group: "Americas", id: "G56889",name: "VTech Socrates" },
  { group: "Americas", id: "G32",   name: "Vectrex" },
  { group: "Americas", id: "G44",   name: "Vic-20" },
  { group: "Americas", id: "G22",   name: "Virtual Boy" },
  { group: "Americas", id: "G57",   name: "Wholesale" },
  { group: "Americas", id: "G11",   name: "Wii" },
  { group: "Americas", id: "G47",   name: "Wii U" },
  { group: "Americas", id: "G151",  name: "WonderSwan" },
  { group: "Americas", id: "G152",  name: "WonderSwan Color" },
  { group: "Americas", id: "G8",    name: "Xbox" },
  { group: "Americas", id: "G10",   name: "Xbox 360" },
  { group: "Americas", id: "G54",   name: "Xbox One" },
  { group: "Americas", id: "G7585", name: "Xbox Series X" },
  { group: "Americas", id: "G44257",name: "ZX Spectrum" },

  // ── PAL / Europe ───────────────────────────────────────────────
  { group: "PAL", id: "G68531",name: "PAL 3DO" },
  { group: "PAL", id: "G153",  name: "PAL Amiga CD32" },
  { group: "PAL", id: "G72181",name: "PAL Amstrad GX4000" },
  { group: "PAL", id: "G72094",name: "PAL Atari 2600" },
  { group: "PAL", id: "G62701",name: "PAL Atari 7800" },
  { group: "PAL", id: "G61287",name: "PAL Evercade" },
  { group: "PAL", id: "G73",   name: "PAL GameBoy" },
  { group: "PAL", id: "G80",   name: "PAL GameBoy Advance" },
  { group: "PAL", id: "G77",   name: "PAL GameBoy Color" },
  { group: "PAL", id: "G70",   name: "PAL Gamecube" },
  { group: "PAL", id: "G123",  name: "PAL MSX" },
  { group: "PAL", id: "G127",  name: "PAL MSX2" },
  { group: "PAL", id: "G141",  name: "PAL Mega Drive 32X" },
  { group: "PAL", id: "G63150",name: "PAL N-Gage" },
  { group: "PAL", id: "G58",   name: "PAL NES" },
  { group: "PAL", id: "G61530",name: "PAL Neo Geo Pocket" },
  { group: "PAL", id: "G37074",name: "PAL Neo Geo Pocket Color" },
  { group: "PAL", id: "G94",   name: "PAL Nintendo 3DS" },
  { group: "PAL", id: "G62",   name: "PAL Nintendo 64" },
  { group: "PAL", id: "G78",   name: "PAL Nintendo DS" },
  { group: "PAL", id: "G87",   name: "PAL Nintendo Switch" },
  { group: "PAL", id: "G80188",name: "PAL Nintendo Switch 2" },
  { group: "PAL", id: "G84",   name: "PAL PSP" },
  { group: "PAL", id: "G72",   name: "PAL Playstation" },
  { group: "PAL", id: "G63",   name: "PAL Playstation 2" },
  { group: "PAL", id: "G75",   name: "PAL Playstation 3" },
  { group: "PAL", id: "G86",   name: "PAL Playstation 4" },
  { group: "PAL", id: "G7469", name: "PAL Playstation 5" },
  { group: "PAL", id: "G101",  name: "PAL Playstation Vita" },
  { group: "PAL", id: "G65",   name: "PAL Sega Dreamcast" },
  { group: "PAL", id: "G121",  name: "PAL Sega Game Gear" },
  { group: "PAL", id: "G51",   name: "PAL Sega Master System" },
  { group: "PAL", id: "G139",  name: "PAL Sega Mega CD" },
  { group: "PAL", id: "G71",   name: "PAL Sega Mega Drive" },
  { group: "PAL", id: "G138",  name: "PAL Sega Pico" },
  { group: "PAL", id: "G97",   name: "PAL Sega Saturn" },
  { group: "PAL", id: "G61",   name: "PAL Super Nintendo" },
  { group: "PAL", id: "G133",  name: "PAL Vectrex" },
  { group: "PAL", id: "G134",  name: "PAL Videopac G7000" },
  { group: "PAL", id: "G135",  name: "PAL Videopac G7400" },
  { group: "PAL", id: "G85",   name: "PAL Wii" },
  { group: "PAL", id: "G96",   name: "PAL Wii U" },
  { group: "PAL", id: "G88",   name: "PAL Xbox" },
  { group: "PAL", id: "G89",   name: "PAL Xbox 360" },
  { group: "PAL", id: "G95",   name: "PAL Xbox One" },
  { group: "PAL", id: "G7586", name: "PAL Xbox Series X" },

  // ── Japan ──────────────────────────────────────────────────────
  { group: "Japan", id: "G68532",name: "JP 3DO" },
  { group: "Japan", id: "G112",  name: "JP GameBoy" },
  { group: "Japan", id: "G79",   name: "JP GameBoy Advance" },
  { group: "Japan", id: "G113",  name: "JP GameBoy Color" },
  { group: "Japan", id: "G98",   name: "JP Gamecube" },
  { group: "Japan", id: "G68060",name: "JP LaserActive" },
  { group: "Japan", id: "G122",  name: "JP MSX" },
  { group: "Japan", id: "G128",  name: "JP MSX2" },
  { group: "Japan", id: "G115",  name: "JP Neo Geo AES" },
  { group: "Japan", id: "G43342",name: "JP Neo Geo CD" },
  { group: "Japan", id: "G114",  name: "JP Neo Geo MVS" },
  { group: "Japan", id: "G59835",name: "JP Neo Geo Pocket" },
  { group: "Japan", id: "G129",  name: "JP Neo Geo Pocket Color" },
  { group: "Japan", id: "G119",  name: "JP Nintendo 3DS" },
  { group: "Japan", id: "G99",   name: "JP Nintendo 64" },
  { group: "Japan", id: "G111",  name: "JP Nintendo DS" },
  { group: "Japan", id: "G100",  name: "JP Nintendo Switch" },
  { group: "Japan", id: "G80189",name: "JP Nintendo Switch 2" },
  { group: "Japan", id: "G82",   name: "JP PC Engine" },
  { group: "Japan", id: "G154",  name: "JP PC Engine CD" },
  { group: "Japan", id: "G110",  name: "JP PSP" },
  { group: "Japan", id: "G107",  name: "JP Playstation" },
  { group: "Japan", id: "G108",  name: "JP Playstation 2" },
  { group: "Japan", id: "G109",  name: "JP Playstation 3" },
  { group: "Japan", id: "G118",  name: "JP Playstation 4" },
  { group: "Japan", id: "G7470", name: "JP Playstation 5" },
  { group: "Japan", id: "G106",  name: "JP Playstation Vita" },
  { group: "Japan", id: "G64",   name: "JP Sega Dreamcast" },
  { group: "Japan", id: "G74",   name: "JP Sega Game Gear" },
  { group: "Japan", id: "G6900", name: "JP Sega Mark III" },
  { group: "Japan", id: "G140",  name: "JP Sega Mega CD" },
  { group: "Japan", id: "G105",  name: "JP Sega Mega Drive" },
  { group: "Japan", id: "G137",  name: "JP Sega Pico" },
  { group: "Japan", id: "G67",   name: "JP Sega Saturn" },
  { group: "Japan", id: "G142",  name: "JP Super 32X" },
  { group: "Japan", id: "G76",   name: "JP Virtual Boy" },
  { group: "Japan", id: "G102",  name: "JP Wii" },
  { group: "Japan", id: "G104",  name: "JP Wii U" },
  { group: "Japan", id: "G125",  name: "JP Xbox" },
  { group: "Japan", id: "G124",  name: "JP Xbox 360" },
  { group: "Japan", id: "G126",  name: "JP Xbox One" },
  { group: "Japan", id: "G7587", name: "JP Xbox Series X" },

  // ── Asian English ──────────────────────────────────────────────
  { group: "Asian English", id: "G56638",name: "Asian English Nintendo 3DS" },
  { group: "Asian English", id: "G59682",name: "Asian English PSP" },
  { group: "Asian English", id: "G70756",name: "Asian English Playstation 2" },
  { group: "Asian English", id: "G56634",name: "Asian English Playstation 3" },
  { group: "Asian English", id: "G56635",name: "Asian English Playstation 4" },
  { group: "Asian English", id: "G56636",name: "Asian English Playstation 5" },
  { group: "Asian English", id: "G56637",name: "Asian English Playstation Vita" },
  { group: "Asian English", id: "G56633",name: "Asian English Switch" },
  { group: "Asian English", id: "G80190",name: "Asian English Switch 2" },
  { group: "Asian English", id: "G72899",name: "Asian English Xbox" },
  { group: "Asian English", id: "G79471",name: "Asian Xbox 360" },

  // ── Magazines & misc ───────────────────────────────────────────
  { group: "Magazines & misc", id: "G77760",name: "Club Nintendo Magazine" },
  { group: "Magazines & misc", id: "G53043",name: "Dreamcast Magazine" },
  { group: "Magazines & misc", id: "G53047",name: "Electronic Gaming Monthly" },
  { group: "Magazines & misc", id: "G53044",name: "Game Informer" },
  { group: "Magazines & misc", id: "G93674",name: "Game Players" },
  { group: "Magazines & misc", id: "G53046",name: "GamePro" },
  { group: "Magazines & misc", id: "G81",   name: "Nintendo Power" },
  { group: "Magazines & misc", id: "G77563",name: "Official Nintendo Magazine" },
  { group: "Magazines & misc", id: "G73272",name: "Official US Playstation Magazine" },
  { group: "Magazines & misc", id: "G85742",name: "PAL Dreamcast Magazine" },
  { group: "Magazines & misc", id: "G53045",name: "PC Gamer Magazine" },
  { group: "Magazines & misc", id: "G93657",name: "Retro Gamer Magazine" },
  { group: "Magazines & misc", id: "G85478",name: "Sega Saturn Magazine" },
  { group: "Magazines & misc", id: "G26297",name: "Strategy Guide" },
];

/** Group order for rendering optgroups. */
export const CONSOLE_GROUPS = [
  "Americas",
  "PAL",
  "Japan",
  "Asian English",
];

// separated from CONSOLE_GROUPS — these aren't consoles
export const MAGAZINES = CONSOLES.filter(c => c.group === "Magazines & misc");
